### PR TITLE
Add ultrasonic sensor source code to /app (two files are currently the same)

### PR DESCRIPTION
**Pull request by bradstevanus1**

### CODE REVIEW

**Comment by jetkov** [comment]
Sweet. Can you add the files types generated by your IDE to the .gitignore file?

**Comment by bradstevanus1** [comment]
Read to merge!

**Comment by jetkov** [comment]
Your IDE files are still showing up in the commit, can you untrack them and then commit that?

**Comment by bradstevanus1** [comment]
I used git rm -r --cached . to remove and re-add all files for the .gitignore to take effect. Looks like the pull request is showed everything being removed and re-added.

**Comment by jetkov** [comment]
Thats ok since its a merge into a branch, go ahead and squash + merge. 👍  For PRs to master branch we should make sure they are pretty clear for everyone to see the intended changes.

**Pull request merged**
